package yi

import "errors"

// Dayan represents the Great Expansion numbers (81 numerology)
// Used for name stroke analysis for fortune telling
type Dayan struct {
	Number     int    // stroke count (1-81)
	JiXiong    string // fortune (auspicious/inauspicious/semi-auspicious)
	NvMing     string // female fortune judgment
	IsMax      bool   // whether it is the most auspicious
	Gua        string // corresponding hexagram
	TianJiu    string // heavenly nine (e.g., Taiji number)
	YiXiang    string // imagery description
	Foundation string // foundation/career
	Family     string // family
	Health     string // health
	Meaning    string // detailed meaning
}

// Error definitions
var (
	ErrInvalidDayanNumber = errors.New("dayan number must be between 1 and 81")
)

// GetDayan returns the Dayan number data
// number: integer between 1 and 81
func GetDayan(number int) (*Dayan, error) {
	if number < 1 || number > 81 {
		return nil, ErrInvalidDayanNumber
	}
	return &dayanList[number-1], nil
}

// MustGetDayan returns the Dayan number data (ignoring errors)
// If number is invalid, returns zero value
func MustGetDayan(number int) Dayan {
	if number < 1 || number > 81 {
		return Dayan{}
	}
	return dayanList[(number-1)%81]
}

// IsJi returns whether it is an auspicious number
func (d *Dayan) IsJi() bool {
	return d.JiXiong == "吉" || d.JiXiong == "半吉"
}

// IsXiong returns whether it is an inauspicious number
func (d *Dayan) IsXiong() bool {
	return d.JiXiong == "凶"
}

// IsSuitableForFemale returns whether it is suitable for females
func (d *Dayan) IsSuitableForFemale() bool {
	return d.NvMing != "凶"
}

// IsBest returns whether it is the most auspicious number
func (d *Dayan) IsBest() bool {
	return d.IsMax
}

// dayanList is the list of Dayan numbers (81 entries)
// Generated by go generate
var dayanList [81]Dayan

// init function (data is populated in data_generated.go)
func init() {
	// Actual data is in data_generated.go
}
