package yi

import (
	"testing"
)

func qian(gx map[string]*GuaXiang) map[string]*GuaXiang {
	gx["乾坤"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		GuaXiang:        "否",
		GuaMing:         "天地否",
		ChuYao:          "拔茅贞吉，志在君也",
		ChuYaoJiXiong:   "平",
		ErYao:           "大人否，享，不乱群也",
		ErYaoJiXiong:    "平",
		SanYao:          "包羞，位不当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "有命无咎，志行也",
		SiYaoJiXiong:    "吉",
		WuYao:           "大人之吉，位正当也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "否终则倾，何可长也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾艮"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		GuaXiang:        "遁",
		GuaMing:         "天山遁",
		ChuYao:          "遁尾之厉，不往何灾也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "执用黄牛，固志也",
		ErYaoJiXiong:    "平",
		SanYao:          "系遁之厉，有疾惫也。畜臣妾吉，不可大事也",
		SanYaoJiXiong:   "平",
		SiYao:           "君子好遁，小人否也",
		SiYaoJiXiong:    "平",
		WuYao:           "嘉遁贞吉，以正志也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "肥遁无不利，无所疑也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["乾坎"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaXiang:        "讼",
		GuaMing:         "天水讼",
		ChuYao:          "不永所事，讼不可长也；虽小有言，其辩明也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "不克讼，归而逋也；自下讼上，患至掇也",
		ErYaoJiXiong:    "平",
		SanYao:          "食旧德，从上吉也",
		SanYaoJiXiong:   "平",
		SiYao:           "复即命，渝安贞，吉，不失也",
		SiYaoJiXiong:    "吉",
		WuYao:           "讼，元吉，以中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "以讼受服，亦不足敬也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾巽"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		JiXiong:         "",
		GuaXiang:        "姤",
		GuaMing:         "天风姤",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "系于金柅，柔道牵也",
		ChuYaoJiXiong:   "平",
		ErYao:           "包有鱼，义不及宾也",
		ErYaoJiXiong:    "平",
		SanYao:          "其行次且，行未牵也",
		SanYaoJiXiong:   "凶",
		SiYao:           "无鱼之凶，远民也",
		SiYaoJiXiong:    "凶",
		WuYao:           "九五含章，中正也；有陨自天，志不舍命也",
		WuYaoJiXiong:    "平",
		ShangYao:        "姤其角，上穷吝也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾震"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		GuaXiang:        "无妄",
		GuaMing:         "天雷无妄",
		ChuYao:          "无妄之往，得志也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "不耕获，未富也",
		ErYaoJiXiong:    "吉",
		SanYao:          "行人得牛，邑人灾也",
		SanYaoJiXiong:   "凶",
		SiYao:           "可贞无咎，固有之也",
		SiYaoJiXiong:    "平",
		WuYao:           "无妄之药，不可试也",
		WuYaoJiXiong:    "平",
		ShangYao:        "无妄之行，穷之灾也",
		ShangYaoJiXiong: "平",
	}

	gx["乾离"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		JiXiong:         "",
		GuaXiang:        "同人",
		GuaMing:         "天火同人",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "出门同人，又谁咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "同人于宗，吝道也",
		ErYaoJiXiong:    "凶",
		SanYao:          "伏戎于莽，敌刚也，三岁不兴，安行也",
		SanYaoJiXiong:   "凶",
		SiYao:           "乘其墉，义弗克也，其吉，则困而反则也",
		SiYaoJiXiong:    "平",
		WuYao:           "同人之先，以中直也。大师相遇，言相克也",
		WuYaoJiXiong:    "平",
		ShangYao:        "同人于郊，志未得也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾兑"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		GuaXiang:        "履",
		GuaMing:         "天泽履",
		ChuYao:          "素履之往，独行愿也",
		ChuYaoJiXiong:   "平",
		ErYao:           "幽人贞吉，中不自乱也",
		ErYaoJiXiong:    "平",
		SanYao:          "眇能视，不足以有明也。跛能履，不足以与行也。咥人之凶，位不当也。武人为于大君，志刚也",
		SanYaoJiXiong:   "凶",
		SiYao:           "愬愬终吉，志行也",
		SiYaoJiXiong:    "平",
		WuYao:           "夬履贞厉。位正当也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "元吉在上，大有庆也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾乾"] = &GuaXiang{
		ShangGua:        "乾为天",
		ShangShu:        0x00,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		JiXiong:         "吉",
		GuaXiang:        "乾",
		GuaMing:         "乾为天",
		GuaYi:           "元亨，利贞",
		GuaYun:          "大哉乾元，万物资始，乃统天。云行雨施，品物流形。大明始终，六位时成，时乘六龙以御天。乾道变化，各正性命，保合大和，乃利贞。首出庶物，万国咸宁",
		XiangYue:        "天行健，君子以自强不息",
		FuHao:           "䷀",
		ChuYao:          "潜龙勿用，阳在下也",
		ChuYaoJiXiong:   "平",
		ErYao:           "见龙在田，德施普也",
		ErYaoJiXiong:    "吉",
		SanYao:          "终日乾乾，反复道也",
		SanYaoJiXiong:   "平",
		SiYao:           "或跃在渊，进无咎也",
		SiYaoJiXiong:    "平",
		WuYao:           "飞龙在天，大人造也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "亢龙有悔，盈不可久也",
		ShangYaoJiXiong: "平",
		Yong:            "天德不可为首也",
		YongJiXiong:     "-",
	}

	return gx
}

func kun(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["坤坤"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		JiXiong:         "",
		GuaXiang:        "坤",
		GuaMing:         "坤为地",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "履霜坚冰，阴始凝也。驯致其道，至坚冰也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之动，直以方也；不习无不利，地道光也",
		ErYaoJiXiong:    "吉",
		SanYao:          "含章可贞，以时发也；或从王事，知光大也",
		SanYaoJiXiong:   "平",
		SiYao:           "括囊无咎，慎不害也",
		SiYaoJiXiong:    "平",
		WuYao:           "黄裳元吉，文在中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "龙战于野，其道穷也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坤艮"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		JiXiong:         "吉",
		GuaXiang:        "谦",
		GuaMing:         "地山谦",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "地中有山，谦。君子以裒多益寡，称物平施",
		FuHao:           "",
		ChuYao:          "谦谦君子，卑以自牧也",
		ChuYaoJiXiong:   "平",
		ErYao:           "鸣谦贞吉，中心得也",
		ErYaoJiXiong:    "吉",
		SanYao:          "劳谦君子，万民服也",
		SanYaoJiXiong:   "吉",
		SiYao:           "无不利，撝谦，不违则也",
		SiYaoJiXiong:    "吉",
		WuYao:           "利用侵伐，征不服也",
		WuYaoJiXiong:    "平",
		ShangYao:        "鸣谦，志未得也；可用行师，征邑国也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坤坎"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaXiang:        "师",
		GuaMing:         "地水师",
		ChuYao:          "师出以律，失律凶也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "在师中吉，承天宠也，王三锡命，怀万邦也",
		ErYaoJiXiong:    "吉",
		SanYao:          "师或舆尸，大无功也",
		SanYaoJiXiong:   "凶",
		SiYao:           "左次无咎，未失常也",
		SiYaoJiXiong:    "平",
		WuYao:           "长子帅师，以中行也；弟子舆尸，使不当也",
		WuYaoJiXiong:    "平",
		ShangYao:        "大君有命，以正功也；小人勿用，必乱邦也",
		ShangYaoJiXiong: "平",
	}

	gx["坤巽"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		GuaXiang:        "升",
		GuaMing:         "地风升",
		ChuYao:          "允升大吉，上合志也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "九二之孚，有喜也",
		ErYaoJiXiong:    "平",
		SanYao:          "升虚邑，无所疑也",
		SanYaoJiXiong:   "平",
		SiYao:           "王用亨于岐山，顺事也",
		SiYaoJiXiong:    "吉",
		WuYao:           "贞吉升阶，大得志也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "冥升在上，消不富也",
		ShangYaoJiXiong: "平",
	}

	gx["坤震"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		JiXiong:         "",
		GuaXiang:        "复",
		GuaMing:         "地雷复",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "不远之复，以修身也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "休复之吉，以下仁也",
		ErYaoJiXiong:    "吉",
		SanYao:          "频复之厉，义无咎也",
		SanYaoJiXiong:   "平",
		SiYao:           "中行独复，以从道也",
		SiYaoJiXiong:    "平",
		WuYao:           "敦复无悔，中以自考也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "迷复之凶，反君道也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坤离"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		GuaXiang:        "明夷",
		GuaMing:         "地火明夷",
		ChuYao:          "君子于行，义不食也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之吉，顺以则也",
		ErYaoJiXiong:    "吉",
		SanYao:          "南狩之志，乃大得也",
		SanYaoJiXiong:   "平",
		SiYao:           "入于左腹，获心意也",
		SiYaoJiXiong:    "平",
		WuYao:           "箕子之贞，明不可息也",
		WuYaoJiXiong:    "平",
		ShangYao:        "初登于天，照四国也。后入于地，失则也",
		ShangYaoJiXiong: "凶",
	}

	gx["坤兑"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		GuaXiang:        "临",
		GuaMing:         "地泽临",
		ChuYao:          "咸临贞吉，志行正也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "咸临，吉无不利，未顺命也",
		ErYaoJiXiong:    "吉",
		SanYao:          "甘临，位不当也。即忧之，咎不长也",
		SanYaoJiXiong:   "凶",
		SiYao:           "至临无咎，位当也",
		SiYaoJiXiong:    "平",
		WuYao:           "大君之宜，行中之谓也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "敦临之吉，志在内也",
		ShangYaoJiXiong: "吉",
	}

	gx["坤乾"] = &GuaXiang{
		ShangGua:        "坤为地",
		ShangShu:        0x07,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		GuaXiang:        "泰",
		GuaMing:         "地天泰",
		ChuYao:          "拔茅征吉，志在外也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "包荒，得尚于中行，以光大也",
		ErYaoJiXiong:    "吉",
		SanYao:          "无往不复，天地际也",
		SanYaoJiXiong:   "平",
		SiYao:           "翩翩不富，皆失实也；不戒以孚，中心愿也",
		SiYaoJiXiong:    "平",
		WuYao:           "以祉元吉，中以行愿也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "城复于隍，其命乱也",
		ShangYaoJiXiong: "凶",
	}
	return gx
}

func gen(gx map[string]*GuaXiang) map[string]*GuaXiang {
	gx["艮坤"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "山地剥",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "剥床以足，以灭下也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "剥床以辨，未有与也",
		ErYaoJiXiong:    "凶",
		SanYao:          "剥之无咎，失上下也",
		SanYaoJiXiong:   "平",
		SiYao:           "剥床以肤，切近灾也",
		SiYaoJiXiong:    "凶",
		WuYao:           "以宫人宠，终无尤也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "君子得舆，民所载也；小人剥庐，终不可用也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["艮艮"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		GuaMing:         "艮为山",
		ChuYao:          "艮其趾，未失正也",
		ChuYaoJiXiong:   "平",
		ErYao:           "不拯其随，未退听也",
		ErYaoJiXiong:    "凶",
		SanYao:          "艮其限，危薰心也",
		SanYaoJiXiong:   "凶",
		SiYao:           "艮其身，止诸躬也",
		SiYaoJiXiong:    "平",
		WuYao:           "艮其辅，以中正也",
		WuYaoJiXiong:    "平",
		ShangYao:        "敦艮之吉，以厚终也",
		ShangYaoJiXiong: "吉",
	}

	gx["艮坎"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaMing:         "山水蒙",
		ChuYao:          "利用刑人，以正法也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "子克家，刚柔接也",
		ErYaoJiXiong:    "吉",
		SanYao:          "勿用娶女，行不顺也",
		SanYaoJiXiong:   "凶",
		SiYao:           "困蒙之吝，独远实也",
		SiYaoJiXiong:    "凶",
		WuYao:           "童蒙之吉，顺以巽也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "利用御寇，上下顺也",
		ShangYaoJiXiong: "平",
	}
	gx["艮巽"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		GuaMing:         "山风蛊",
		ChuYao:          "干父之蛊，意承考也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "干母之蛊，得中道也",
		ErYaoJiXiong:    "平",
		SanYao:          "干父之蛊，终无咎也",
		SanYaoJiXiong:   "凶",
		SiYao:           "裕父之蛊，往未得也",
		SiYaoJiXiong:    "凶",
		WuYao:           "干父之蛊，承以德也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "不事王侯，志可则也",
		ShangYaoJiXiong: "平",
	}
	gx["艮震"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		GuaMing:         "山雷颐",
		ChuYao:          "观我朵颐，亦不足贵也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "六二征凶，行失类也",
		ErYaoJiXiong:    "凶",
		SanYao:          "十年勿用，道大悖也",
		SanYaoJiXiong:   "凶",
		SiYao:           "颠颐之吉，上施光也",
		SiYaoJiXiong:    "吉",
		WuYao:           "居贞之吉，顺以从上也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "由颐厉吉，大有庆也",
		ShangYaoJiXiong: "吉",
	}

	gx["艮离"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		GuaMing:         "山火贲",
		ChuYao:          "舍车而徒，义弗乘也",
		ChuYaoJiXiong:   "平",
		ErYao:           "贲其须，与上兴也",
		ErYaoJiXiong:    "平",
		SanYao:          "永贞之吉，终莫之陵也",
		SanYaoJiXiong:   "吉",
		SiYao:           "六四当位疑也。匪寇婚媾，终无尤也",
		SiYaoJiXiong:    "平",
		WuYao:           "六五之吉，有喜也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "白贲无咎，上得志也",
		ShangYaoJiXiong: "平",
	}

	gx["艮兑"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		GuaMing:         "山泽损",
		ChuYao:          "已事遄往，尚合志也",
		ChuYaoJiXiong:   "平",
		ErYao:           "九二利贞，中以为志也",
		ErYaoJiXiong:    "凶",
		SanYao:          "一人行，三则疑也",
		SanYaoJiXiong:   "平",
		SiYao:           "损其疾，亦可喜也",
		SiYaoJiXiong:    "平",
		WuYao:           "六五元吉，自上佑也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "弗损益之，大得志也",
		ShangYaoJiXiong: "吉",
	}
	gx["艮乾"] = &GuaXiang{
		ShangGua:        "艮为山",
		ShangShu:        0x06,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		GuaMing:         "山天大畜",
		ChuYao:          "有厉利已，不犯灾也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "舆说輹，中无尤也",
		ErYaoJiXiong:    "凶",
		SanYao:          "利有攸往，上合志也",
		SanYaoJiXiong:   "平",
		SiYao:           "六四元吉，有喜也",
		SiYaoJiXiong:    "吉",
		WuYao:           "六五之吉，有庆也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "何天之衢，道大行也",
		ShangYaoJiXiong: "吉",
	}

	gx["坎坤"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		GuaMing:         "水地比",
		ChuYao:          "比之初六，有它吉也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "比之自内，不自失也",
		ErYaoJiXiong:    "吉",
		SanYao:          "比之匪人，不亦伤乎",
		SanYaoJiXiong:   "凶",
		SiYao:           "外比于贤，以从上也",
		SiYaoJiXiong:    "吉",
		WuYao:           "显比之吉，位正中也。舍逆取顺，失前禽也。邑人不诫，上使中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "比之无首，无所终也",
		ShangYaoJiXiong: "凶",
	}
	return gx
}

func kan(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["坎艮"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		GuaMing:         "水山蹇",
		ChuYao:          "往蹇来誉，宜待也",
		ChuYaoJiXiong:   "平",
		ErYao:           "王臣蹇蹇，终无尤也",
		ErYaoJiXiong:    "凶",
		SanYao:          "往蹇来反，内喜之也",
		SanYaoJiXiong:   "平",
		SiYao:           "往蹇来连，当位实也",
		SiYaoJiXiong:    "凶",
		WuYao:           "大蹇朋来，以中节也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "往蹇来硕，志在内也；利见大人，以从贵也",
		ShangYaoJiXiong: "吉",
	}

	gx["坎坎"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaMing:         "坎为水",
		ChuYao:          "习坎入坎，失道凶也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "求小得，未出中也",
		ErYaoJiXiong:    "平",
		SanYao:          "来之坎坎，终无功也",
		SanYaoJiXiong:   "凶",
		SiYao:           "樽酒簋贰，刚柔际也",
		SiYaoJiXiong:    "平",
		WuYao:           "坎不盈，中未大也",
		WuYaoJiXiong:    "平",
		ShangYao:        "上六失道，凶三岁也",
		ShangYaoJiXiong: "凶",
	}
	gx["坎巽"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		GuaMing:         "水风井",
		ChuYao:          "井泥不食，下也。旧井无禽，时舍也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "井谷射鲋，无与也",
		ErYaoJiXiong:    "凶",
		SanYao:          "井渫不食，行恻也。求王明，受福也",
		SanYaoJiXiong:   "平",
		SiYao:           "井甃无咎，修井也",
		SiYaoJiXiong:    "平",
		WuYao:           "寒泉之食，中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "元吉在上，大成也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
	}
	gx["坎震"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		GuaMing:         "水雷屯",
		ChuYao:          "虽盘桓，志行正也；以贵下贱，大得民也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之难，乘刚也；十年乃字，反常也",
		ErYaoJiXiong:    "平",
		SanYao:          "即鹿无虞，以纵禽也。君子舍之，往吝，穷也",
		SanYaoJiXiong:   "凶",
		SiYao:           "求而往，明也",
		SiYaoJiXiong:    "吉",
		WuYao:           "屯其膏，施未光也",
		WuYaoJiXiong:    "平",
		ShangYao:        "泣血涟如，何可长也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
	}

	gx["坎离"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		GuaMing:         "水火既济",
		ChuYao:          "曳其轮，义无咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "七日得，以中道也",
		ErYaoJiXiong:    "平",
		SanYao:          "三年克之，惫也",
		SanYaoJiXiong:   "凶",
		SiYao:           "终日戒，有所疑也",
		SiYaoJiXiong:    "平",
		WuYao:           "东邻杀牛，不如西邻之时也。实受其福，吉大来也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "濡其首厉，何可久也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坎兑"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		GuaMing:         "水泽节",
		ChuYao:          "不出户庭，知通塞也",
		ChuYaoJiXiong:   "平",
		ErYao:           "不出门庭，失时极也",
		ErYaoJiXiong:    "凶",
		SanYao:          "不节之嗟，又谁咎也",
		SanYaoJiXiong:   "平",
		SiYao:           "安节之亨，承上道也",
		SiYaoJiXiong:    "吉",
		WuYao:           "甘节之吉，居位中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "苦节贞凶，其道穷也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坎乾"] = &GuaXiang{
		ShangGua:        "坎为水",
		ShangShu:        0x05,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		GuaMing:         "水天需",
		ChuYao:          "需于郊，不犯难行也；利用恒，无咎，未失常也",
		ChuYaoJiXiong:   "平",
		ErYao:           "需于沙，衍在中也；虽小有言，以终吉也",
		ErYaoJiXiong:    "吉",
		SanYao:          "需于泥，灾在外也。自我致寇，敬慎不败也",
		SanYaoJiXiong:   "凶",
		SiYao:           "需于血，顺以听也",
		SiYaoJiXiong:    "平",
		WuYao:           "酒食贞吉，以中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "不速之客，敬之终吉；虽不当位，未大失也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func xun(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["巽坤"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		GuaMing:         "风地观",
		ChuYao:          "初六童观，小人道也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "窥观女贞，亦可丑也",
		ErYaoJiXiong:    "平",
		SanYao:          "观我生进退，未失道也",
		SanYaoJiXiong:   "平",
		SiYao:           "观国之光，尚宾也",
		SiYaoJiXiong:    "平",
		WuYao:           "观我生，观民也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "观其生，志未平也",
		ShangYaoJiXiong: "平",
	}

	gx["巽艮"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		GuaMing:         "风山渐",
		ChuYao:          "小子之厉，义无咎也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "饮食衎衎，不素饱也",
		ErYaoJiXiong:    "吉",
		SanYao:          "夫征不复，离群丑也。妇孕不育，失其道也。利用御寇，顺相保也",
		SanYaoJiXiong:   "凶",
		SiYao:           "或得其桷，顺以巽也",
		SiYaoJiXiong:    "平",
		WuYao:           "终莫之胜，吉，得所愿也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "其羽可用为仪，吉，不可乱也",
		ShangYaoJiXiong: "吉",
	}

	gx["巽坎"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaMing:         "风水涣",
		ChuYao:          "初六之吉，顺也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "涣奔其机，得愿也",
		ErYaoJiXiong:    "平",
		SanYao:          "涣其躬，志在外也",
		SanYaoJiXiong:   "平",
		SiYao:           "涣其群，元吉，光大也",
		SiYaoJiXiong:    "吉",
		WuYao:           "王居无咎，正位也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "涣其血，远害也",
		ShangYaoJiXiong: "平",
	}
	gx["巽巽"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		GuaMing:         "巽为风",
		ChuYao:          "进退，志疑也。利武人之贞，志治也",
		ChuYaoJiXiong:   "平",
		ErYao:           "纷若之吉，得中也",
		ErYaoJiXiong:    "吉",
		SanYao:          "频巽之吝，志穷也",
		SanYaoJiXiong:   "凶",
		SiYao:           "田获三品，有功也",
		SiYaoJiXiong:    "吉",
		WuYao:           "九五之吉，位中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "巽在床下，上穷也；丧其资斧，正乎凶也",
		ShangYaoJiXiong: "凶",
	}
	gx["巽震"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		GuaMing:         "风雷益",
		ChuYao:          "元吉无咎，下不厚事也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "或益之，自外来也",
		ErYaoJiXiong:    "吉",
		SanYao:          "益用凶事，固有之也",
		SanYaoJiXiong:   "平",
		SiYao:           "告公从，以益志也",
		SiYaoJiXiong:    "平",
		WuYao:           "有孚惠心，勿问之矣。惠我德，大得志也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "莫益之，偏辞也。或击之，自外来也",
		ShangYaoJiXiong: "凶",
	}

	gx["巽离"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		GuaMing:         "风火家人",
		ChuYao:          "闲有家，志未变也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之吉，顺以巽也",
		ErYaoJiXiong:    "吉",
		SanYao:          "家人嗃嗃，未失也；妇子嘻嘻，失家节也",
		SanYaoJiXiong:   "凶",
		SiYao:           "富家大吉，顺在位也",
		SiYaoJiXiong:    "吉",
		WuYao:           "王假有家，交相爱也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "威如之吉，反身之谓也",
		ShangYaoJiXiong: "吉",
	}

	gx["巽兑"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		GuaMing:         "风泽中孚",
		ChuYao:          "初九虞吉，志未变也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "其子和之，中心愿也",
		ErYaoJiXiong:    "吉",
		SanYao:          "或鼓或罢，位不当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "马匹亡，绝类上也",
		SiYaoJiXiong:    "平",
		WuYao:           "有孚挛如，位正当也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "翰音登于天，何可长也",
		ShangYaoJiXiong: "凶",
	}
	gx["巽乾"] = &GuaXiang{
		ShangGua:        "巽为风",
		ShangShu:        0x04,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		GuaMing:         "风天小畜",
		ChuYao:          "复自道，其义吉也",
		ChuYaoJiXiong:   "平",
		ErYao:           "牵复在中，亦不自失也",
		ErYaoJiXiong:    "吉",
		SanYao:          "夫妻反目，不能正室也",
		SanYaoJiXiong:   "凶",
		SiYao:           "有孚惕出，上合志也",
		SiYaoJiXiong:    "平",
		WuYao:           "有孚挛如，不独富也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "既雨既处，德积载也。君子征凶，有所疑也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func zhen(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["震坤"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		GuaMing:         "雷地豫",
		ChuYao:          "初六鸣豫，志穷凶也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "不终日，贞吉，以中正也",
		ErYaoJiXiong:    "吉",
		SanYao:          "盱豫有悔，位不当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "由豫大有得。志大行也",
		SiYaoJiXiong:    "吉",
		WuYao:           "六五贞疾，乘刚也。恒不死，中未亡也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "冥豫在上，何可长也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震艮"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		GuaMing:         "雷山小过",
		ChuYao:          "飞鸟以凶，不可如何也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "不及其君，臣不可过也",
		ErYaoJiXiong:    "平",
		SanYao:          "从或戕之，凶如何也",
		SanYaoJiXiong:   "凶",
		SiYao:           "弗过遇之，位不当也。往厉必戒，终不可长也",
		SiYaoJiXiong:    "平",
		WuYao:           "密云不雨，已上也",
		WuYaoJiXiong:    "平",
		ShangYao:        "弗遇过之，已亢也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震坎"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaMing:         "雷水解",
		ChuYao:          "刚柔之际，义无咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "九二贞吉，得中道也",
		ErYaoJiXiong:    "吉",
		SanYao:          "负且乘，亦可丑也；自我致戎，又谁咎也",
		SanYaoJiXiong:   "凶",
		SiYao:           "解而拇，未当位也",
		SiYaoJiXiong:    "凶",
		WuYao:           "君子有解，小人退也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "公用射隼，以解悖也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["震巽"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		GuaMing:         "雷风恒",
		ChuYao:          "浚恒之凶，始求深也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "九二悔亡，能久中也",
		ErYaoJiXiong:    "平",
		SanYao:          "不恒其德，无所容也",
		SanYaoJiXiong:   "凶",
		SiYao:           "久非其位，安得禽也",
		SiYaoJiXiong:    "凶",
		WuYao:           "妇人贞吉，从一而终也。夫子制义，从妇凶也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "振恒在上，大无功也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["震震"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		GuaMing:         "震为雷",
		ChuYao:          "震来虩虩，恐致福也。笑言哑哑，后有则也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "震来厉，乘刚也",
		ErYaoJiXiong:    "凶",
		SanYao:          "震苏苏，位不当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "震遂泥，未光也",
		SiYaoJiXiong:    "凶",
		WuYao:           "震往来厉，危行也。其事在中，大无丧也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "震索索，未得中也。虽凶无咎，畏邻戒也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震离"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		GuaMing:         "雷火丰",
		ChuYao:          "虽旬无咎，过旬灾也",
		ChuYaoJiXiong:   "平",
		ErYao:           "有孚发若，信以发志也",
		ErYaoJiXiong:    "吉",
		SanYao:          "丰其沛，不可大事也。折其右肱，终不可用也",
		SanYaoJiXiong:   "平",
		SiYao:           "丰其蔀，位不当也。日中见斗，幽不明也。遇其夷主，吉，行也",
		SiYaoJiXiong:    "平",
		WuYao:           "六五之吉，有庆也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "丰其屋，天际翔也。窥其户，阒其无人，自藏也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震兑"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		GuaMing:         "雷泽归妹",
		ChuYao:          "归妹以娣，以恒也。跛能履吉，相承也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "利幽人之贞，未变常也",
		ErYaoJiXiong:    "平",
		SanYao:          "归妹以须，未当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "愆期之志，有待而行也",
		SiYaoJiXiong:    "平",
		WuYao:           "帝乙归妹，不如其娣之袂良也。其位在中，以贵行也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "上六无实，承虚筐也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["震乾"] = &GuaXiang{
		ShangGua:        "震为雷",
		ShangShu:        0x03,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		GuaMing:         "雷天大壮",
		ChuYao:          "壮于趾，其孚穷也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "九二贞吉，以中也",
		ErYaoJiXiong:    "吉",
		SanYao:          "小人用壮，君子罔也",
		SanYaoJiXiong:   "凶",
		SiYao:           "藩决不羸，尚往也",
		SiYaoJiXiong:    "吉",
		WuYao:           "丧羊于易，位不当也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "不能退，不能遂，不详也；艰则吉，咎不长也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func li(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["离坤"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		GuaMing:         "火地晋",
		ChuYao:          "晋如摧如，独行正也。裕无咎，未受命也",
		ChuYaoJiXiong:   "平",
		ErYao:           "受之介福，以中正也",
		ErYaoJiXiong:    "吉",
		SanYao:          "众允之，志上行也",
		SanYaoJiXiong:   "平",
		SiYao:           "鼫鼠贞厉，位不当也",
		SiYaoJiXiong:    "凶",
		WuYao:           "失得勿恤，往有庆也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "维用伐邑，道未光也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["离艮"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		GuaMing:         "火山旅",
		ChuYao:          "旅琐琐，志穷灾也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "得童仆贞，终无尤也",
		ErYaoJiXiong:    "吉",
		SanYao:          "旅焚其次，亦以伤矣。以旅与下，其义丧也",
		SanYaoJiXiong:   "凶",
		SiYao:           "旅于处，未得位也。得其资斧，心未快也",
		SiYaoJiXiong:    "凶",
		WuYao:           "终以誉命，上逮也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "以旅在上，其义焚也。丧牛于易，终莫之闻也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["离坎"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaMing:         "火水未济",
		ChuYao:          "濡其尾，亦不知极也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "九二贞吉，中以行正也",
		ErYaoJiXiong:    "吉",
		SanYao:          "未济征凶，位不当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "贞吉悔亡，志行也",
		SiYaoJiXiong:    "吉",
		WuYao:           "君子之光，其晖吉也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "饮酒濡首，亦不知节也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["离巽"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "火风鼎",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "鼎颠趾，未悖也。利出否，以从贵也",
		ChuYaoJiXiong:   "平",
		ErYao:           "鼎有实，慎所之也。我仇有疾，终无尤也",
		ErYaoJiXiong:    "吉",
		SanYao:          "鼎耳革，失其义也",
		SanYaoJiXiong:   "平",
		SiYao:           "覆公餗，信如何也",
		SiYaoJiXiong:    "凶",
		WuYao:           "鼎黄耳，中以为实也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "玉铉在上，刚柔节也",
		ShangYaoJiXiong: "吉 ",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["离震"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		GuaMing:         "火雷噬嗑",
		ChuYao:          "屦校灭趾，不行也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "噬肤灭鼻，乘刚也",
		ErYaoJiXiong:    "平",
		SanYao:          "遇毒，位不当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "利艰贞吉，未光也",
		SiYaoJiXiong:    "吉",
		WuYao:           "贞厉无咎，得当也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "何校灭耳，聪不明也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["离离"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		GuaMing:         "离为火",
		ChuYao:          "履错之敬，以辟咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "黄离元吉，得中道也",
		ErYaoJiXiong:    "吉",
		SanYao:          "日昃之离，何可久也",
		SanYaoJiXiong:   "凶",
		SiYao:           "突如其来如，无所容也",
		SiYaoJiXiong:    "凶",
		WuYao:           "六五之吉，离王公也",
		WuYaoJiXiong:    "平",
		ShangYao:        "王用出征，以正邦也",
		ShangYaoJiXiong: "吉 ",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["离兑"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		GuaMing:         "火泽睽",
		ChuYao:          "见恶人，以辟咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "遇主于巷，未失道也",
		ErYaoJiXiong:    "平",
		SanYao:          "见舆曳，位不当也；无初有终，遇刚也",
		SanYaoJiXiong:   "凶",
		SiYao:           "交孚无咎，志行也",
		SiYaoJiXiong:    "平",
		WuYao:           "厥宗噬肤，往有庆也",
		WuYaoJiXiong:    "平",
		ShangYao:        "遇雨之吉，群疑亡也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["离乾"] = &GuaXiang{
		ShangGua:        "离为火",
		ShangShu:        0x02,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "火天大有",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "大有初九，无交害也",
		ChuYaoJiXiong:   "平",
		ErYao:           "大车以载，积中不败也",
		ErYaoJiXiong:    "吉",
		SanYao:          "公用亨于天子，小人害也",
		SanYaoJiXiong:   "平",
		SiYao:           "匪其彭，无咎，明辩晰也",
		SiYaoJiXiong:    "平",
		WuYao:           "厥孚交如，信以发志也；威如之吉，易而无备也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "大有上吉，自天祐也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func dui(gx map[string]*GuaXiang) map[string]*GuaXiang {
	gx["兑坤"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "坤为地",
		XiaShu:          0x07,
		GuaMing:         "泽地萃",
		ChuYao:          "乃乱乃萃，其志乱也",
		ChuYaoJiXiong:   "平",
		ErYao:           "引吉无咎，中未变也",
		ErYaoJiXiong:    "吉",
		SanYao:          "往无咎，上巽也",
		SanYaoJiXiong:   "凶",
		SiYao:           "大吉无咎，位不当也",
		SiYaoJiXiong:    "平",
		WuYao:           "萃有位，志未光也",
		WuYaoJiXiong:    "平",
		ShangYao:        "赍咨涕洟，未安上也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兑艮"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "艮为山",
		XiaShu:          0x06,
		JiXiong:         "吉",
		GuaXiang:        "山上有泽，咸。君子以虚受人",
		GuaMing:         "泽山咸",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "咸其拇，志在外也",
		ChuYaoJiXiong:   "平",
		ErYao:           "虽凶居吉，顺不害也",
		ErYaoJiXiong:    "平",
		SanYao:          "咸其股，亦不处也。志在随人，所执下也",
		SanYaoJiXiong:   "平",
		SiYao:           "贞吉悔亡，未感害也。憧憧往来，未光大也",
		SiYaoJiXiong:    "平",
		WuYao:           "咸其脢，志末也",
		WuYaoJiXiong:    "平",
		ShangYao:        "咸其辅颊舌，滕口说也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兑坎"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "坎为水",
		XiaShu:          0x05,
		GuaMing:         "泽水困",
		ChuYao:          "入于幽谷，幽不明也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "困于洒食，中有庆也",
		ErYaoJiXiong:    "平",
		SanYao:          "据于疾藜，乘刚也；入于其宫，不见其妻，不祥也",
		SanYaoJiXiong:   "凶",
		SiYao:           "来徐徐，志在下也。虽不当位，有与也",
		SiYaoJiXiong:    "凶",
		WuYao:           "劓刖，志未得也。乃徐有说，以中直也。利用祭祀，受福也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "困于葛藟，未当也。动悔有悔，吉行也",
		ShangYaoJiXiong: "平",
	}

	gx["兑巽"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "巽为风",
		XiaShu:          0x04,
		GuaMing:         "泽风大过",
		ChuYao:          "藉用白茅，柔在下也",
		ChuYaoJiXiong:   "平",
		ErYao:           "老夫女妻，过以相与也",
		ErYaoJiXiong:    "吉",
		SanYao:          "栋桡之凶，不可以有辅也",
		SanYaoJiXiong:   "凶",
		SiYao:           "栋隆之吉，不桡乎下也",
		SiYaoJiXiong:    "吉",
		WuYao:           "枯杨生花，何可久也。老妇土夫，亦可丑也",
		WuYaoJiXiong:    "平",
		ShangYao:        "过涉之凶，不可咎也",
		ShangYaoJiXiong: "凶",
	}

	gx["兑震"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "震为雷",
		XiaShu:          0x03,
		GuaMing:         "泽雷随",
		ChuYao:          "官有渝，从正吉也；出门交有功，不失也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "系小子，弗兼与也",
		ErYaoJiXiong:    "凶",
		SanYao:          "系丈夫，志舍下也",
		SanYaoJiXiong:   "平",
		SiYao:           "随有获，其义凶也。有孚在道，明功也",
		SiYaoJiXiong:    "平",
		WuYao:           "孚于嘉吉，位正中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "拘系之，上穷也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兑离"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "离为火",
		XiaShu:          0x02,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "泽火革",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "巩用黄牛，不可以有为也",
		ChuYaoJiXiong:   "平",
		ErYao:           "己日革之，行有嘉也",
		ErYaoJiXiong:    "吉",
		SanYao:          "革言三就，又何之矣",
		SanYaoJiXiong:   "凶",
		SiYao:           "改命之吉，信志也",
		SiYaoJiXiong:    "平",
		WuYao:           "大人虎变，其文炳也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "君子豹变，其文蔚也。小人革面，顺以从君也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兑兑"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "兑为泽",
		XiaShu:          0x01,
		JiXiong:         "吉",
		GuaXiang:        "丽泽，兑。君子以朋友讲习",
		GuaMing:         "兑为泽",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "和兑之吉，行未疑也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "孚兑之吉，信志也",
		ErYaoJiXiong:    "吉",
		SanYao:          "来兑之凶，位不当也",
		SanYaoJiXiong:   "凶",
		SiYao:           "九四之喜，有庆也",
		SiYaoJiXiong:    "平",
		WuYao:           "孚于剥，位正当也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "上六引兑，未光也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兑乾"] = &GuaXiang{
		ShangGua:        "兑为泽",
		ShangShu:        0x01,
		XiaGua:          "乾为天",
		XiaShu:          0x00,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "泽天夬",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "不胜而往，咎也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "有戎勿恤，得中道也",
		ErYaoJiXiong:    "凶",
		SanYao:          "君子夬夬，终无咎也",
		SanYaoJiXiong:   "凶",
		SiYao:           "其行次且，位不当也；闻言不信，聪不明也",
		SiYaoJiXiong:    "凶",
		WuYao:           "中行无咎，中未光也",
		WuYaoJiXiong:    "平",
		ShangYao:        "无号之凶，终不可长也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	return gx
}

func TestSetGuaXiang(t *testing.T) {
	gx := make(map[string]*GuaXiang)
	gx = qian(gx)
	gx = kun(gx)
	gx = gen(gx)
	gx = kan(gx)
	gx = xun(gx)
	gx = zhen(gx)
	gx = li(gx)
	gx = dui(gx)
	setGuaXiang(gx)

}

func TestGetGuaXiang(t *testing.T) {
	if len(getGuaXiang()) != 64 {
		t.Log("not enough", getGuaXiang())
	}

}
