package yi

// ============================================================================
// LiuQin (六亲) - Six Relations method
// ============================================================================
//
// 六亲是六爻预测学中的核心概念，根据卦爻所在的地支与卦宫五行的生克关系
// 来确定六亲属性：
//
//   - 父母（生我者）: 生助、庇护、文书、契约
//   - 兄弟（同我者）: 竞争、劫财、同辈、朋友
//   - 妻财（我克者）: 财富、妻室、粮食、物资
//   - 子孙（我生者）: 子嗣、福气、解忧、医药
//   - 官鬼（克我者）: 官司、鬼祟、祸患、丈夫（女命）
//
// 六亲与五行的对应由卦宫五行决定，同一卦宫内的六亲归属相同。
//
// Reference:
//   - 《增删卜易》野鹤老人
//   - 《卜筮正宗》王洪绪

// LiuQin represents the Six Relations type.
type LiuQin int

const (
	LQFuMu    LiuQin = iota // 父母 (Parents)
	LQXiongDi               // 兄弟 (Siblings)
	LQQiCai                 // 妻财 (Wife/Wealth)
	LQZiSun                 // 子孙 (Children)
	LQGuanGui               // 官鬼 (Officer/Ghost)
	LQCount
)

// String returns the Chinese name of LiuQin.
func (lq LiuQin) String() string {
	switch lq {
	case LQFuMu:
		return "父母"
	case LQXiongDi:
		return "兄弟"
	case LQQiCai:
		return "妻财"
	case LQZiSun:
		return "子孙"
	case LQGuanGui:
		return "官鬼"
	default:
		return ""
	}
}

// Description returns a brief description of LiuQin.
func (lq LiuQin) Description() string {
	switch lq {
	case LQFuMu:
		return "生我者，主庇护文书"
	case LQXiongDi:
		return "同我者，主竞争劫财"
	case LQQiCai:
		return "我克者，主财富妻室"
	case LQZiSun:
		return "我生者，主子嗣福德"
	case LQGuanGui:
		return "克我者，主官非祸患"
	default:
		return ""
	}
}

// GetLiuQin calculates the LiuQin of a given WuXing relative to the GuaGong WuXing.
// guaGongWX: the WuXing of the hexagram palace (卦宫五行)
// yaoWX: the WuXing of the line/branch (爻支五行)
//
// The relationship determines LiuQin:
//   - yaoWX is generated by guaGongWX → 父母 (FuMu)    [生我]
//   - yaoWX is same as guaGongWX       → 兄弟 (XiongDi) [同我]
//   - yaoWX is controlled by guaGongWX  → 妻财 (QiCai)  [我克]
//   - yaoWX is generated from guaGongWX → 子孙 (ZiSun)  [我生]
//   - yaoWX controls guaGongWX          → 官鬼 (GuanGui)[克我]
func GetLiuQin(guaGongWX, yaoWX WuXing) LiuQin {
	if guaGongWX == yaoWX {
		return LQXiongDi // 同我
	}
	if guaGongWX.Sheng() == yaoWX {
		return LQZiSun // 我生
	}
	if guaGongWX.Ke() == yaoWX {
		return LQQiCai // 我克
	}
	if yaoWX.Sheng() == guaGongWX {
		return LQFuMu // 生我
	}
	if yaoWX.Ke() == guaGongWX {
		return LQGuanGui // 克我
	}
	return LQCount // should never reach
}

// GetGuaGongWuXing returns the WuXing of the hexagram palace.
// Each of the 8 palaces has a governing WuXing:
//   - 乾宫 → 金 (Metal)
//   - 兑宫 → 金 (Metal)
//   - 离宫 → 火 (Fire)
//   - 震宫 → 木 (Wood)
//   - 巽宫 → 木 (Wood)
//   - 坎宫 → 水 (Water)
//   - 艮宫 → 土 (Earth)
//   - 坤宫 → 土 (Earth)
func GetGuaGongWuXing(bagua Bagua) WuXing {
	switch bagua {
	case Qian, Dui:
		return Metal
	case Li:
		return Fire
	case Zhen, Xun:
		return Wood
	case Kan:
		return Water
	case Gen, Kun:
		return Earth
	default:
		return 0
	}
}

// GetLiuQinForGua returns a mapping of WuXing → LiuQin for a given hexagram palace.
// This is the complete LiuQin lookup table for one palace.
func GetLiuQinForGua(guaGongWX WuXing) map[WuXing]LiuQin {
	result := make(map[WuXing]LiuQin, 5)
	for _, wx := range []WuXing{Wood, Fire, Earth, Metal, Water} {
		result[wx] = GetLiuQin(guaGongWX, wx)
	}
	return result
}
