package main

import (
	"encoding/csv"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	fmt.Println("Generating yi data...")

	// 读取CSV并生成Go代码
	if err := generateData(); err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Done!")
}

func generateData() error {
	var sb strings.Builder

	sb.WriteString("// Code generated by go generate. DO NOT EDIT.\n\n")
	sb.WriteString("package yi\n\n")

	// 生成八卦数据
	sb.WriteString("func init() {\n")
	sb.WriteString("\t// 初始化八卦数据\n")

	// 读取8gua.csv
	if err := generateBagua(&sb); err != nil {
		return err
	}

	// 读取64gua.csv
	if err := generate64Gua(&sb); err != nil {
		return err
	}

	// 读取81shu.csv
	if err := generate81Shu(&sb); err != nil {
		return err
	}

	sb.WriteString("}\n")

	return os.WriteFile("data_generated.go", []byte(sb.String()), 0644)
}

func generateBagua(sb *strings.Builder) error {
	file, err := os.Open("data/8gua.csv")
	if err != nil {
		return err
	}
	defer file.Close()

	reader := csv.NewReader(file)
	reader.Comma = ','

	// 跳过表头
	if _, err := reader.Read(); err != nil {
		return err
	}

	records, err := reader.ReadAll()
	if err != nil {
		return err
	}

	sb.WriteString("\t// 八卦数据\n")
	for _, record := range records {
		if len(record) < 3 {
			continue
		}
		name := record[0]
		num := record[1]
		symbol := record[2]
		if name == "" || num == "" {
			continue
		}
		n, _ := strconv.Atoi(num)
		sb.WriteString(fmt.Sprintf("\tbaguaNames[%d] = %q\n", n, name))
		sb.WriteString(fmt.Sprintf("\tbaguaSymbols[%d] = %q\n", n, symbol))
	}

	return nil
}

func generate64Gua(sb *strings.Builder) error {
	file, err := os.Open("data/64gua.csv")
	if err != nil {
		return err
	}
	defer file.Close()

	reader := csv.NewReader(file)
	reader.Comma = ','

	// 跳过表头
	if _, err := reader.Read(); err != nil {
		return err
	}

	records, err := reader.ReadAll()
	if err != nil {
		return err
	}

	sb.WriteString("\n\t// 六十四卦数据\n")
	for i, record := range records {
		if len(record) < 31 {
			continue
		}
		index := record[1]
		sb.WriteString(fmt.Sprintf("\tguaStore[%q] = &Gua{\n", index))
		sb.WriteString(fmt.Sprintf("\t\tXu: %s,\n", record[0]))
		sb.WriteString(fmt.Sprintf("\t\tIndex: %q,\n", record[1]))
		sb.WriteString(fmt.Sprintf("\t\tShang: %q,\n", record[2]))
		sb.WriteString(fmt.Sprintf("\t\tShangNum: %s,\n", record[3]))
		sb.WriteString(fmt.Sprintf("\t\tXia: %q,\n", record[4]))
		sb.WriteString(fmt.Sprintf("\t\tXiaNum: %s,\n", record[5]))
		sb.WriteString(fmt.Sprintf("\t\tJiXiong: %q,\n", record[6]))
		sb.WriteString(fmt.Sprintf("\t\tXiang: %q,\n", record[7]))
		sb.WriteString(fmt.Sprintf("\t\tMing: %q,\n", record[8]))
		sb.WriteString(fmt.Sprintf("\t\tYi: %q,\n", record[9]))
		sb.WriteString(fmt.Sprintf("\t\tSymbol: %q,\n", record[10]))
		sb.WriteString(fmt.Sprintf("\t\tYong: %q,\n", record[29]))
		sb.WriteString(fmt.Sprintf("\t\tYongJiXiong: %q,\n", record[30]))
		sb.WriteString("\t}\n")
		_ = i
	}

	return nil
}

func generate81Shu(sb *strings.Builder) error {
	file, err := os.Open("data/81shu.csv")
	if err != nil {
		return err
	}
	defer file.Close()

	reader := csv.NewReader(file)
	reader.Comma = ','

	// 跳过表头
	if _, err := reader.Read(); err != nil {
		return err
	}

	records, err := reader.ReadAll()
	if err != nil {
		return err
	}

	sb.WriteString("\n\t// 大衍之数81数理\n")
	for _, record := range records {
		if len(record) < 11 {
			continue
		}
		num := record[0]
		n, _ := strconv.Atoi(num)
		isMax := "false"
		if strings.TrimSpace(record[3]) == "最吉" {
			isMax = "true"
		}

		sb.WriteString(fmt.Sprintf("\tdayanList[%d] = Dayan{\n", n-1))
		sb.WriteString(fmt.Sprintf("\t\tNumber: %s,\n", num))
		sb.WriteString(fmt.Sprintf("\t\tJiXiong: %q,\n", record[1]))
		sb.WriteString(fmt.Sprintf("\t\tNvMing: %q,\n", record[2]))
		sb.WriteString(fmt.Sprintf("\t\tIsMax: %s,\n", isMax))
		sb.WriteString(fmt.Sprintf("\t\tGua: %q,\n", record[4]))
		sb.WriteString(fmt.Sprintf("\t\tTianJiu: %q,\n", record[5]))
		sb.WriteString(fmt.Sprintf("\t\tYiXiang: %q,\n", record[6]))
		sb.WriteString(fmt.Sprintf("\t\tFoundation: %q,\n", record[7]))
		sb.WriteString(fmt.Sprintf("\t\tFamily: %q,\n", record[8]))
		sb.WriteString(fmt.Sprintf("\t\tHealth: %q,\n", record[9]))
		sb.WriteString(fmt.Sprintf("\t\tMeaning: %q,\n", record[10]))
		sb.WriteString("\t}\n")
	}

	return nil
}
