package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// JSONData represents the complete data structure from JSON files
type JSONData struct {
	Bagua   []BaguaJSON   `json:"bagua"`
	Gua     []GuaJSON     `json:"gua"`
	Dayan   []DayanJSON   `json:"dayan"`
	WenYan  []WenYanJSON  `json:"wenyan"`
	JiaZi   []JiaZiJSON   `json:"jiazi"`
	GuaGong []GuaGongJSON `json:"guagong"`
	JieGua  []JieGuaJSON  `json:"jiegua"`
}

// BaguaJSON represents a single trigram
type BaguaJSON struct {
	Name              string `json:"name"`
	Num               int    `json:"num"`
	Symbol            string `json:"symbol"`
	XianTianNum       int    `json:"xian_tian_num"`
	HouTianNum        int    `json:"hou_tian_num"`
	SymbolName        string `json:"symbol_name"`
	Binary            string `json:"binary"`
	XianTianRemainder int    `json:"xian_tian_remainder"`
	WuXing            string `json:"wuxing"`
	Image             string `json:"image"`
	Property          string `json:"property"`
	Direction         string `json:"direction"`
	Person            string `json:"person"`
	Body              string `json:"body"`
	Animal            string `json:"animal"`
	Location          string `json:"location"`
	Object            string `json:"object"`
	Season            string `json:"season"`
	Door              string `json:"door"`
	PurpleStar        string `json:"purple_star"`
	TianYunStar       string `json:"tianyun_star"`
	ZhaiJuStar        string `json:"zhaiju_star"`
	JiXiongPosition   string `json:"jixiong_position"`
}

// GuaJSON represents a single hexagram
type GuaJSON struct {
	Xu          int        `json:"xu"`
	Index       string     `json:"index"`
	ShangMing   string     `json:"shang_ming"`
	ShangNum    int        `json:"shang_num"`
	XiaMing     string     `json:"xia_ming"`
	XiaNum      int        `json:"xia_num"`
	JiXiong     string     `json:"jixiong"`
	GuaName     string     `json:"gua_name"`
	Ming        string     `json:"ming"`
	GuaYi       string     `json:"gua_yi"`
	GuaSymbol   string     `json:"gua_symbol"`
	TuanText    string     `json:"tuan_text"`
	XiangText   string     `json:"xiang_text"`
	Yaos        [6]YaoJSON `json:"yaos"`
	Yong        string     `json:"yong"`
	YongJiXiong string     `json:"yong_jixiong"`
}

// YaoJSON represents a single line in a hexagram
type YaoJSON struct {
	Ci      string `json:"ci"`
	JiXiong string `json:"jixiong"`
	NvMing  string `json:"nvming"`
}

// DayanJSON represents a single Dayan number
type DayanJSON struct {
	Number     int    `json:"number"`
	JiXiong    string `json:"jixiong"`
	NvMing     string `json:"nvming"`
	IsMax      bool   `json:"is_max"`
	Gua        string `json:"gua"`
	TianJiu    string `json:"tian_jiu"`
	YiXiang    string `json:"yixiang"`
	Foundation string `json:"foundation"`
	Family     string `json:"family"`
	Health     string `json:"health"`
	Meaning    string `json:"meaning"`
}

// WenYanJSON represents WenYan (文言) data
type WenYanJSON struct {
	Index   string            `json:"index"`
	Entries []WenYanEntryJSON `json:"entries"`
}

// WenYanEntryJSON represents a single WenYan passage
type WenYanEntryJSON struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}

// JiaZiJSON represents a single JiaZi (甲子) entry
type JiaZiJSON struct {
	Index   int    `json:"index"`
	Name    string `json:"name"`
	TianGan string `json:"tian_gan"`
	DiZhi   string `json:"di_zhi"`
	NaYin   string `json:"wu_xing"` // JSON uses wu_xing but struct uses NaYin
	YinYang string `json:"yin_yang"`
}

// GuaGongJSON represents a hexagram's palace assignment
type GuaGongJSON struct {
	Palace   int    `json:"palace"`
	Position int    `json:"position"`
	Index    string `json:"index"`
}

// JieGuaJSON represents detailed interpretation for one hexagram
type JieGuaJSON struct {
	Index   string `json:"index"`
	ShiYi   string `json:"shiyi"`
	AiQing  string `json:"aiqing"`
	CaiYun  string `json:"caiyun"`
	KaoShi  string `json:"kaoshi"`
	JianKang string `json:"jiankang"`
	ChuXing string `json:"chuxing"`
	GuanSi  string `json:"guansi"`
	JiaZhai string `json:"jiazhai"`
}

func main() {
	fmt.Println("Generating yi data from JSON...")

	if err := generateFromJSON(); err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Done!")
}

func generateFromJSON() error {
	// Load all JSON data
	data, err := loadAllJSON()
	if err != nil {
		return fmt.Errorf("load JSON: %w", err)
	}

	// Generate Go code
	var sb strings.Builder

	sb.WriteString("// Code generated by go generate from JSON. DO NOT EDIT.\n\n")
	sb.WriteString("package yi\n\n")
	sb.WriteString("func init() {\n")

	if err := generateBaguaFromJSON(&sb, data.Bagua); err != nil {
		return fmt.Errorf("generate bagua: %w", err)
	}

	if err := generateGuaFromJSON(&sb, data.Gua); err != nil {
		return fmt.Errorf("generate gua: %w", err)
	}

	if err := generateDayanFromJSON(&sb, data.Dayan); err != nil {
		return fmt.Errorf("generate dayan: %w", err)
	}

	if err := generateWenYanFromJSON(&sb, data.WenYan); err != nil {
		return fmt.Errorf("generate wenyan: %w", err)
	}

	if err := generateJiaZiFromJSON(&sb, data.JiaZi); err != nil {
		return fmt.Errorf("generate jiazi: %w", err)
	}

	if err := generateGuaGongFromJSON(&sb, data.GuaGong); err != nil {
		return fmt.Errorf("generate guagong: %w", err)
	}

	if err := generateJieGuaFromJSON(&sb, data.JieGua); err != nil {
		return fmt.Errorf("generate jiegua: %w", err)
	}

	sb.WriteString("}\n")

	// Write to file (data.gen.go)
	if err := os.WriteFile("data.gen.go", []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	return nil
}

func loadAllJSON() (*JSONData, error) {
	data := &JSONData{}

	// Load bagua.json
	if err := loadJSONFile("data/bagua.json", &data.Bagua); err != nil {
		return nil, fmt.Errorf("bagua: %w", err)
	}
	fmt.Printf("Loaded bagua.json: %d entries\n", len(data.Bagua))

	// Load gua.json
	if err := loadJSONFile("data/gua.json", &data.Gua); err != nil {
		return nil, fmt.Errorf("gua: %w", err)
	}
	fmt.Printf("Loaded gua.json: %d entries\n", len(data.Gua))

	// Load dayan.json
	if err := loadJSONFile("data/dayan.json", &data.Dayan); err != nil {
		return nil, fmt.Errorf("dayan: %w", err)
	}
	fmt.Printf("Loaded dayan.json: %d entries\n", len(data.Dayan))

	// Load wenyan.json
	if err := loadJSONFile("data/wenyan.json", &data.WenYan); err != nil {
		return nil, fmt.Errorf("wenyan: %w", err)
	}
	fmt.Printf("Loaded wenyan.json: %d entries\n", len(data.WenYan))

	// Load jiazi.json
	if err := loadJSONFile("data/jiazi.json", &data.JiaZi); err != nil {
		return nil, fmt.Errorf("jiazi: %w", err)
	}
	fmt.Printf("Loaded jiazi.json: %d entries\n", len(data.JiaZi))

	// Load guagong.json
	if err := loadJSONFile("data/guagong.json", &data.GuaGong); err != nil {
		return nil, fmt.Errorf("guagong: %w", err)
	}
	fmt.Printf("Loaded guagong.json: %d entries\n", len(data.GuaGong))

	// Load jiegua.json
	if err := loadJSONFile("data/jiegua.json", &data.JieGua); err != nil {
		return nil, fmt.Errorf("jiegua: %w", err)
	}
	fmt.Printf("Loaded jiegua.json: %d entries\n", len(data.JieGua))

	return data, nil
}

func loadJSONFile(path string, v interface{}) error {
	file, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if err := json.Unmarshal(file, v); err != nil {
		return fmt.Errorf("parse %s: %w", path, err)
	}
	return nil
}

func generateBaguaFromJSON(sb *strings.Builder, bagua []BaguaJSON) error {
	sb.WriteString("\t// Bagua data (8 trigrams)\n")
	for _, b := range bagua {
		if b.Num < 0 || b.Num > 7 {
			continue
		}
		sb.WriteString(fmt.Sprintf("\tbaguaNames[%d] = %q\n", b.Num, b.Name))
		sb.WriteString(fmt.Sprintf("\tbaguaSymbols[%d] = %q\n", b.Num, b.Symbol))
	}
	sb.WriteString("\n")
	return nil
}

func generateGuaFromJSON(sb *strings.Builder, gua []GuaJSON) error {
	sb.WriteString("\t// 64 Gua data (hexagrams)\n")
	for _, g := range gua {
		sb.WriteString(fmt.Sprintf("\tguaStore[%q] = &Gua{\n", g.Index))
		sb.WriteString(fmt.Sprintf("\t\tXu: %d,\n", g.Xu))
		sb.WriteString(fmt.Sprintf("\t\tIndex: %q,\n", g.Index))
		sb.WriteString(fmt.Sprintf("\t\tShangMing: %q,\n", g.ShangMing))
		sb.WriteString(fmt.Sprintf("\t\tShangNum: %d,\n", g.ShangNum))
		sb.WriteString(fmt.Sprintf("\t\tXiaMing: %q,\n", g.XiaMing))
		sb.WriteString(fmt.Sprintf("\t\tXiaNum: %d,\n", g.XiaNum))
		sb.WriteString(fmt.Sprintf("\t\tJiXiong: %q,\n", g.JiXiong))
		sb.WriteString(fmt.Sprintf("\t\tGuaName: %q,\n", g.GuaName))
		sb.WriteString(fmt.Sprintf("\t\tMing: %q,\n", g.Ming))
		sb.WriteString(fmt.Sprintf("\t\tGuaYi: %q,\n", g.GuaYi))
		sb.WriteString(fmt.Sprintf("\t\tGuaSymbol: %q,\n", g.GuaSymbol))
		sb.WriteString(fmt.Sprintf("\t\tTuanText: %q,\n", g.TuanText))
		sb.WriteString(fmt.Sprintf("\t\tXiangText: %q,\n", g.XiangText))

		sb.WriteString("\t\tYaos: [6]*Yao{")
		for i, y := range g.Yaos {
			if i > 0 {
				sb.WriteString(", ")
			}
			if y.Ci != "" {
				sb.WriteString(fmt.Sprintf("&Yao{Ci: %q, JiXiong: %q, NvMing: %q}", y.Ci, y.JiXiong, y.NvMing))
			} else {
				sb.WriteString("nil")
			}
		}
		sb.WriteString("},\n")

		sb.WriteString(fmt.Sprintf("\t\tYong: %q,\n", g.Yong))
		sb.WriteString(fmt.Sprintf("\t\tYongJiXiong: %q,\n", g.YongJiXiong))
		sb.WriteString("\t}\n")
	}
	sb.WriteString("\n")
	return nil
}

func generateDayanFromJSON(sb *strings.Builder, dayan []DayanJSON) error {
	sb.WriteString("\t// Dayan 81 data (great expansion numbers)\n")
	for _, d := range dayan {
		if d.Number < 1 || d.Number > 81 {
			continue
		}
		sb.WriteString(fmt.Sprintf("\tdayanList[%d] = Dayan{\n", d.Number-1))
		sb.WriteString(fmt.Sprintf("\t\tNumber: %d,\n", d.Number))
		sb.WriteString(fmt.Sprintf("\t\tJiXiong: %q,\n", d.JiXiong))
		sb.WriteString(fmt.Sprintf("\t\tNvMing: %q,\n", d.NvMing))
		sb.WriteString(fmt.Sprintf("\t\tIsMax: %v,\n", d.IsMax))
		sb.WriteString(fmt.Sprintf("\t\tGua: %q,\n", d.Gua))
		sb.WriteString(fmt.Sprintf("\t\tTianJiu: %q,\n", d.TianJiu))
		sb.WriteString(fmt.Sprintf("\t\tYiXiang: %q,\n", d.YiXiang))
		sb.WriteString(fmt.Sprintf("\t\tFoundation: %q,\n", d.Foundation))
		sb.WriteString(fmt.Sprintf("\t\tFamily: %q,\n", d.Family))
		sb.WriteString(fmt.Sprintf("\t\tHealth: %q,\n", d.Health))
		sb.WriteString(fmt.Sprintf("\t\tMeaning: %q,\n", d.Meaning))
		sb.WriteString("\t}\n")
	}
	sb.WriteString("\n")
	return nil
}

func generateWenYanFromJSON(sb *strings.Builder, wenyan []WenYanJSON) error {
	sb.WriteString("\t// WenYan (文言) data\n")
	sb.WriteString("\twenYanStore = map[string][]WenYanEntry{\n")
	for _, w := range wenyan {
		if len(w.Entries) == 0 {
			continue
		}
		sb.WriteString(fmt.Sprintf("\t\t%q: {\n", w.Index))
		for _, e := range w.Entries {
			sb.WriteString(fmt.Sprintf("\t\t\t{Title: %q, Text: %q},\n", e.Title, e.Text))
		}
		sb.WriteString("\t\t},\n")
	}
	sb.WriteString("\t}\n\n")
	return nil
}

func generateJiaZiFromJSON(sb *strings.Builder, jiazi []JiaZiJSON) error {
	sb.WriteString("\t// JiaZi (甲子) 60-cycle data\n")
	for _, j := range jiazi {
		if j.Index < 1 || j.Index > 60 {
			continue
		}
		sb.WriteString(fmt.Sprintf("\tjiaZiList[%d] = JiaZiInfo{\n", j.Index-1))
		sb.WriteString(fmt.Sprintf("\t\tIndex: %d,\n", j.Index))
		sb.WriteString(fmt.Sprintf("\t\tName: %q,\n", j.Name))
		sb.WriteString(fmt.Sprintf("\t\tTianGan: %q,\n", j.TianGan))
		sb.WriteString(fmt.Sprintf("\t\tDiZhi: %q,\n", j.DiZhi))
		sb.WriteString(fmt.Sprintf("\t\tNaYin: %q,\n", j.NaYin))
		sb.WriteString(fmt.Sprintf("\t\tYinYang: %q,\n", j.YinYang))
		sb.WriteString("\t}\n")
	}
	sb.WriteString("\n")
	return nil
}

func generateGuaGongFromJSON(sb *strings.Builder, guagong []GuaGongJSON) error {
	sb.WriteString("\t// GuaGong (八宫归属) and GuaPosition data\n")
	sb.WriteString("\tguaPositionStore = map[string]GuaPosition{\n")
	for _, g := range guagong {
		sb.WriteString(fmt.Sprintf("\t\t%q: %d, // %s\n", g.Index, g.Position, guaPositionName(g.Position)))
	}
	sb.WriteString("\t}\n\n")

	sb.WriteString("\tguaGongStore = map[string]Bagua{\n")
	for _, g := range guagong {
		sb.WriteString(fmt.Sprintf("\t\t%q: %d,\n", g.Index, g.Palace))
	}
	sb.WriteString("\t}\n\n")
	return nil
}

func guaPositionName(pos int) string {
	names := []string{"BenGong", "YiShi", "ErShi", "SanShi", "SiShi", "WuShi", "YouHun", "GuiHun"}
	if pos >= 0 && pos < len(names) {
		return names[pos]
	}
	return "Unknown"
}

func generateJieGuaFromJSON(sb *strings.Builder, jiegua []JieGuaJSON) error {
	sb.WriteString("\t// JieGua (卦解读) detailed interpretation data\n")
	sb.WriteString("\tguaJieDuStore = map[string]*GuaJieDu{\n")
	for _, j := range jiegua {
		sb.WriteString(fmt.Sprintf("\t\t%q: &GuaJieDu{\n", j.Index))
		sb.WriteString(fmt.Sprintf("\t\t\tMing: %q,\n", j.Index))
		sb.WriteString(fmt.Sprintf("\t\t\tShiYe: %q,\n", j.ShiYi))
		sb.WriteString(fmt.Sprintf("\t\t\tAiQing: %q,\n", j.AiQing))
		sb.WriteString(fmt.Sprintf("\t\t\tCaiYun: %q,\n", j.CaiYun))
		sb.WriteString(fmt.Sprintf("\t\t\tKaoShi: %q,\n", j.KaoShi))
		sb.WriteString(fmt.Sprintf("\t\t\tJianKang: %q,\n", j.JianKang))
		sb.WriteString(fmt.Sprintf("\t\t\tChuXing: %q,\n", j.ChuXing))
		sb.WriteString(fmt.Sprintf("\t\t\tGuanSi: %q,\n", j.GuanSi))
		sb.WriteString(fmt.Sprintf("\t\t\tJiaZhai: %q,\n", j.JiaZhai))
		sb.WriteString("\t\t},\n")
	}
	sb.WriteString("\t}\n\n")
	return nil
}
